### 회원가입
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "email": "example3@example.com",
    "password": "Ex@mp1e!!",
    "passwordConfirm": "Ex@mp1e!!",
    "nickname": "예매자3"
}